port: 3000
zang:
  accountSid: testahh
  authToken: testahhh
  phoneNumber: +19892560442
locationName: 'super duper 7 a'
database:
  host: 127.0.0.1
  port: 27017
  name: butler
openTone: 9
dbPath: './storage'
phoneNumber: '+5555555555'

